version: '2'
services:
  api:
    image: opsclick-api-deploy:latest
    container_name: api
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - ./env/common
    links:
      - mongodb
      - redis
      - celery
    tty: true

  worker:
    image: opsclick-api-deploy:latest
    volumes:
      - .:/app
    command: su -m apiuser -c "celery worker -A api -Q default -n default@%h -l info"
    links:
      - mongodb
      - redis
      - celery
    tty: true

  mongodb:
    image: mongo:latest
    container_name: mongo
    volumes:
      - datadb:/data/db
    tty: true

  celery:
    image: celery:latest
    container_name: celery
    links:
      - redis
    environment:
      CELERY_BROKER_URL: "redis://redis/0"
    tty: true

  redis:
    image: redis:latest
    container_name: redis
    tty: true

volumes:
  datadb:
    driver: local
